### ISSUE TITLE
Feature request: More examples

### ISSUE THREAD

**Issue by binary64** [mrseanryan/eslint-plugin-ts-ban-snippets#23]
Hi great plugin, it would be awesome to have a whole bunch of examples in a terse format on the README.md

**Comment by mrseanryan** [comment]
thank you @binary64 - good to hear !

The README does have some examples - the format is a bit verbose indeed.

Would it help if I add a short summary to each?

Like:  "To detect if some tests are disabled with code like `it.only` then use a config like this:"

OR can you think of a better way?

Thank you
Sean

**Comment by mrseanryan** [comment]
Fixed with version `1.2.2` - let me know if you have more suggestions :)
